import { Rule, Document } from "@/types/rule";

export const mockDocuments: Document[] = [
  {
    id: "doc-1",
    name: "Politique de remboursement 2024.pdf",
    type: "pdf",
    uploadedAt: "2024-01-15T10:30:00Z",
    status: "completed",
    rulesCount: 12,
  },
  {
    id: "doc-2",
    name: "Règles de validation commandes.pptx",
    type: "pptx",
    uploadedAt: "2024-01-14T14:20:00Z",
    status: "completed",
    rulesCount: 8,
  },
  {
    id: "doc-3",
    name: "Procédures d'approbation.pdf",
    type: "pdf",
    uploadedAt: "2024-01-10T09:15:00Z",
    status: "completed",
    rulesCount: 15,
  },
];

export const mockRules: Rule[] = [
  {
    id: "rule-1",
    documentId: "doc-1",
    documentName: "Politique de remboursement 2024.pdf",
    text: "Les remboursements doivent être traités dans un délai de 14 jours ouvrables à compter de la réception de la demande.",
    conditions: ["Demande reçue", "Délai < 14 jours ouvrables", "Statut validé"],
    domain: "Finance",
    tags: ["remboursement", "délai", "finance"],
    confidence: 0.95,
    source: { page: 3, section: "Section 2.1 - Délais de traitement" },
    createdAt: "2024-01-15T10:35:00Z",
  },
  {
    id: "rule-2",
    documentId: "doc-1",
    documentName: "Politique de remboursement 2024.pdf",
    text: "Un remboursement ne peut excéder le montant initial de la transaction.",
    conditions: ["Montant remboursement ≤ Montant transaction"],
    domain: "Finance",
    tags: ["remboursement", "montant", "validation"],
    confidence: 0.98,
    source: { page: 4, section: "Section 2.3 - Montants" },
    createdAt: "2024-01-15T10:35:00Z",
  },
  {
    id: "rule-3",
    documentId: "doc-2",
    documentName: "Règles de validation commandes.pptx",
    text: "Toute commande supérieure à 10 000€ nécessite l'approbation d'un manager niveau 2 ou supérieur.",
    conditions: ["Montant > 10000€", "Approbateur niveau ≥ 2"],
    domain: "Achats",
    tags: ["commande", "approbation", "seuil"],
    confidence: 0.92,
    source: { page: 7, section: "Slide 7 - Workflow d'approbation" },
    createdAt: "2024-01-14T14:25:00Z",
  },
  {
    id: "rule-4",
    documentId: "doc-2",
    documentName: "Règles de validation commandes.pptx",
    text: "Les commandes urgentes (délai < 48h) requièrent une justification écrite obligatoire.",
    conditions: ["Délai livraison < 48h", "Justification fournie"],
    domain: "Achats",
    tags: ["commande", "urgence", "justification"],
    confidence: 0.88,
    source: { page: 9, section: "Slide 9 - Cas particuliers" },
    createdAt: "2024-01-14T14:25:00Z",
  },
  {
    id: "rule-5",
    documentId: "doc-3",
    documentName: "Procédures d'approbation.pdf",
    text: "Les congés excédant 2 semaines consécutives doivent être approuvés 30 jours à l'avance minimum.",
    conditions: ["Durée congé > 14 jours", "Demande ≥ 30 jours avant"],
    domain: "RH",
    tags: ["congés", "approbation", "délai"],
    confidence: 0.91,
    source: { page: 12, section: "Chapitre 4 - Congés" },
    createdAt: "2024-01-10T09:20:00Z",
  },
  {
    id: "rule-6",
    documentId: "doc-1",
    documentName: "Politique de remboursement 2024.pdf",
    text: "Les frais de déplacement sont remboursés sur présentation des justificatifs originaux uniquement.",
    conditions: ["Justificatif original fourni", "Type frais = déplacement"],
    domain: "Finance",
    tags: ["remboursement", "frais", "justificatif"],
    confidence: 0.96,
    source: { page: 8, section: "Section 3.2 - Frais de déplacement" },
    createdAt: "2024-01-15T10:35:00Z",
  },
  {
    id: "rule-7",
    documentId: "doc-3",
    documentName: "Procédures d'approbation.pdf",
    text: "Les notes de frais doivent être soumises dans un délai de 30 jours après la dépense.",
    conditions: ["Date soumission - Date dépense ≤ 30 jours"],
    domain: "Finance",
    tags: ["frais", "délai", "soumission"],
    confidence: 0.94,
    source: { page: 5, section: "Section 1.4 - Délais de soumission" },
    createdAt: "2024-01-10T09:20:00Z",
  },
  {
    id: "rule-8",
    documentId: "doc-2",
    documentName: "Règles de validation commandes.pptx",
    text: "Les fournisseurs non référencés nécessitent une validation du service achats avant commande.",
    conditions: ["Fournisseur non référencé", "Validation service achats"],
    domain: "Achats",
    tags: ["fournisseur", "validation", "référencement"],
    confidence: 0.87,
    source: { page: 5, section: "Slide 5 - Fournisseurs" },
    createdAt: "2024-01-14T14:25:00Z",
  },
];
